### ISSUE TITLE
Password mining: Portainer password not detected

### ISSUE THREAD

**Issue by sgofferj** [marius-wieschollek/passwords-webextension#138]
### System Information
- Extension Version: 2.0.4.3887
- App Version: 2021.1.2
- Browser and Version: Google Chrome 88.0.4324.96 / Desktop Linux amd64
- Client OS and Version: Ubuntu 20.04

### Steps to reproduce
1. Go to Portainer web interface
2. Login
3. 

### Expected result
Password should be detected and added

### Actual result
No reaction
Note: I activated the Highlight Login Form Fields debug option and all fields of the login form are highlighted correctly, including the submit button.

### Browser log
<details>
<summary>Browser log</summary>

```
background.js:1 Could not read custom fields Error: Could not read custom fields
    at Object.warning (background.js:1)
    at M.fromObject (background.js:22)
    at M.fromEncryptedData (background.js:22)
    at St.makePasswordFromApiData (background.js:22)
    at St.makeFromApiData (background.js:22)
    at g._dataToModel (background.js:22)
    at background.js:22
    at new Promise (<anonymous>)
    at background.js:22
    at new Promise (<anonymous>) {details: {…}, error: {…}} Error: Could not read custom fields
    at Object.warning (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:5220)
    at M.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:132071)
    at M.fromEncryptedData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:131109)
    at St.makePasswordFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:150880)
    at St.makeFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:150493)
    at g._dataToModel (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:126515)
    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:126376
    at new Promise (<anonymous>)
    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:126355
    at new Promise (<anonymous>)
_addError @ background.js:1
warning @ background.js:1
fromObject @ background.js:22
fromEncryptedData @ background.js:22
makePasswordFromApiData @ background.js:22
makeFromApiData @ background.js:22
_dataToModel @ background.js:22
(anonymous) @ background.js:22
(anonymous) @ background.js:22
_dataToModels @ background.js:22
findAll @ background.js:22
async function (async)
findAll @ background.js:22
_reloadRepository @ background.js:28
_reloadServer @ background.js:28
(anonymous) @ background.js:28
background.js:1 Unexpected end of JSON input SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at k.fromJSON (background.js:22)
    at M.fromObject (background.js:22)
    at M.fromEncryptedData (background.js:22)
    at St.makePasswordFromApiData (background.js:22)
    at St.makeFromApiData (background.js:22)
    at g._dataToModel (background.js:22)
    at background.js:22
    at new Promise (<anonymous>)
    at background.js:22 {details: {…}, error: {…}} SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at k.fromJSON (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:132938)
    at M.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:132012)
    at M.fromEncryptedData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:131109)
    at St.makePasswordFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:150880)
    at St.makeFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:150493)
    at g._dataToModel (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:126515)
    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:126376
    at new Promise (<anonymous>)
    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:126355
_addError @ background.js:1
logError @ background.js:1
exception @ background.js:1
fromObject @ background.js:22
fromEncryptedData @ background.js:22
makePasswordFromApiData @ background.js:22
makeFromApiData @ background.js:22
_dataToModel @ background.js:22
(anonymous) @ background.js:22
(anonymous) @ background.js:22
_dataToModels @ background.js:22
findAll @ background.js:22
async function (async)
findAll @ background.js:22
_reloadRepository @ background.js:28
_reloadServer @ background.js:28
(anonymous) @ background.js:28
background.js:1 undefined {} {details: {…}, error: {…}} "Error
    at Object._getDetailsFromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:6349)
    at Object._addError (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:5708)
    at Object.logError (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:5543)
    at Object._sendMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:11529)"
_addError @ background.js:1
logError @ background.js:1
_sendMessage @ background.js:1
async function (async)
_sendMessage @ background.js:1
(anonymous) @ background.js:1
send @ background.js:1
_sendItem @ background.js:1
(anonymous) @ background.js:1
push @ background.js:1
(anonymous) @ background.js:1
_sendToast @ background.js:1
create @ background.js:1
error @ background.js:1
exception @ background.js:1
fromObject @ background.js:22
fromEncryptedData @ background.js:22
makePasswordFromApiData @ background.js:22
makeFromApiData @ background.js:22
_dataToModel @ background.js:22
(anonymous) @ background.js:22
(anonymous) @ background.js:22
_dataToModels @ background.js:22
findAll @ background.js:22
async function (async)
findAll @ background.js:22
_reloadRepository @ background.js:28
_reloadServer @ background.js:28
(anonymous) @ background.js:28
background.js:1 Uncaught (in promise) {}
_sendMessage @ background.js:1
async function (async)
_sendMessage @ background.js:1
(anonymous) @ background.js:1
send @ background.js:1
_sendItem @ background.js:1
(anonymous) @ background.js:1
push @ background.js:1
(anonymous) @ background.js:1
_sendToast @ background.js:1
create @ background.js:1
error @ background.js:1
exception @ background.js:1
fromObject @ background.js:22
fromEncryptedData @ background.js:22
makePasswordFromApiData @ background.js:22
makeFromApiData @ background.js:22
_dataToModel @ background.js:22
(anonymous) @ background.js:22
(anonymous) @ background.js:22
_dataToModels @ background.js:22
findAll @ background.js:22
async function (async)
findAll @ background.js:22
_reloadRepository @ background.js:28
_reloadServer @ background.js:28
(anonymous) @ background.js:28
```
</details>

**Comment by sgofferj** [comment]
Related to #123. Opened separate issue because the URL in internal and so it can't just be posted to #123 as per instructions in that issue. 
Portainer is a container orchestration tool -> https://www.portainer.io/

**Comment by sgofferj** [comment]
Confirmed working in portainer 2.1.1

**Comment by sgofferj** [comment]
FYI: Fix also fixes it for NodeRED and Gitea
