### ISSUE TITLE
HTTP 412 Response for all authenticated requests from extension after some amount of time

### ISSUE THREAD

**Issue by jfanjoy** [marius-wieschollek/passwords-webextension#144]
### System Information
- Extension Version: 2.1.0
- App Version: 2021.2.0
- Browser and Version: Brave (Chrome) 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)
- Client OS and Version: Arch Linux (5.10.15-arch1-1 #1 SMP PREEMPT Wed, 10 Feb 2021 18:32:40 +0000 x86_64 GNU/Linux)

### Steps to reproduce
1.  There appears to be a session limit for the extension. Upon configuration with an App password from my security settings I am offered an opportunity to provide password and TOTP token. Entering my password and token does log me into the extension, and I am able to use the everything fine for a while. After some amount of time (less than 8 hours) the requests made by the plugin begin receiving 412 errors. No indication that a session timeout has occurred. I can still access passwords, but saving new passwords or generating random passwords will fail. The only solution I have found is completely restarting the browser or reconfiguring the extension with a new app password.
2.  In attempting to gather information the extension detected the changes and required re-authentication. I will have to update this issue with the log data once it begins to fail again. For now the response code is probably a good starting point.
3.  There is a default setting to limit a session to 10 minutes in the app, but I haven't changed this and I assume it's supposed to be for the password app page in nextcloud. I seem to get more than 10 minutes of use out of the extension.

I also have DFA enabled on my account which the extension does see and prompt for.

### Expected result
What should happen? I would expect the browser extension configured with an app password to be able to keep the session open or at minimum detect a failed request and prompt for re-authentication instead of returning the 412 to the user.

### Actual result
What does happen? The app seems to continue working partially, but saving and generating random passwords fails.

### Browser log
<details>
<summary>Browser log</summary>

I enabled the developer mode which triggered a need to relogin in the extension, so I will have to wait until it starts throwing errors to be able to include the logs.

```
In Chrome
 - Open chrome://extensions
 - Enable "Developer mode" in the top right corner
 - Click "Background page" on the extension
 - Copy the content from the "Console" tab
```
</details>

**Comment by jfanjoy** [comment]
Here are most of the headers from a failed request:
```
access-control-allow-origin: chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi
cache-control: no-cache, no-store, must-revalidate
content-length: 74
content-security-policy: default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
content-type: application/json; charset=utf-8
date: Sun, 14 Feb 2021 22:49:39 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
pragma: no-cache
referrer-policy: no-referrer
set-cookie: nc_username=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; secure; HttpOnly
set-cookie: nc_token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; secure; HttpOnly
set-cookie: nc_session_id=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; secure; HttpOnly
set-cookie: nc_username=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; HttpOnly
set-cookie: nc_token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; HttpOnly
set-cookie: nc_session_id=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; HttpOnly
set-cookie: oc6reqvuj0d1=7r7gfssko02ntpfk1gros5q48q; path=/; secure; HttpOnly; SameSite=Lax
strict-transport-security: max-age=15552000; includeSubDomains
x-api-session: 36ca84dd-15ca-476a-b9f9-7b671d099ac9
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-robots-tag: none
x-robots-tag: none
x-xss-protection: 1; mode=block
```

The output in the console from the background page is here as well:

```
HTTP 412 HttpError: HTTP 412
    at Vt.getClass (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:123334)
    at Yt.getClass (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:162513)
    at et._getHttpError (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:138928)
    at et._processJsonResponse (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:138301)
    at et.send (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:136838)
    at async St.generate (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:154620)
    at async o.execute (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/PasswordGenerate.js:1:457)
    at async Object._executeController (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:28:219953)
    at async Array.<anonymous> (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:28:215533)
    at async Object._notifyListeners (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:13504) Object HttpError: HTTP 412
    at Vt.getClass (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:123334)
    at Yt.getClass (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:162513)
    at et._getHttpError (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:138928)
    at et._processJsonResponse (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:138301)
    at et.send (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:136838)
    at async St.generate (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:154620)
    at async o.execute (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/PasswordGenerate.js:1:457)
    at async Object._executeController (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:28:219953)
    at async Array.<anonymous> (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:28:215533)
    at async Object._notifyListeners (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:13504)
_addError @ background.js:1
```

The response body was empty.
