### ISSUE TITLE
Uncaught TypeError: t.querySelectorAll is not a function

### ISSUE THREAD

**Issue by mrohnstock** [marius-wieschollek/passwords-webextension#172]
### System Information
- Extension Version: 2.2.0.4091
- App Version:  2021.4.0
- Browser and Version: Vivaldi 3.7.2218.52
- Client OS and Version: Archlinux

### Steps to reproduce
1. Open DevTools (CTRL + SHIFT + I)
2. Visit any webpage (i.e. Github.com)
3. See the following js-errors:

```
Uncaught TypeError: t.querySelectorAll is not a function
    at o.getPasswordFields (client.js:28)
    at MutationObserver.<anonymous> (client.js:28)
```

![image](https://user-images.githubusercontent.com/823072/114864564-6f9a6280-9df1-11eb-9603-347a12ea11e3.png)

### Expected result
No js-error should get logged

### Actual result
Many js-errors got logged (but the plugin is still working without issues)

### Browser log
<details>
<summary>Browser log</summary>

```
background.js:1 this.options.mode.getValue is not a function TypeError: this.options.mode.getValue is not a function
    at Object.getFilterQuery (background.js:22)
    at Object.getRecommendationsByUrl (background.js:22)
    at Object._updateRecommended (background.js:22)
    at _tabEvent (background.js:22)
    at n._notifyListeners (background.js:1)
    at n.emit (background.js:1)
    at Object._updateTabInfo (background.js:1) Object TypeError: this.options.mode.getValue is not a function
    at Object.getFilterQuery (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:22:33232)
    at Object.getRecommendationsByUrl (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:22:32990)
    at Object._updateRecommended (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:22:34925)
    at _tabEvent (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:22:32271)
    at n._notifyListeners (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:1:102998)
    at n.emit (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:1:102700)
    at Object._updateTabInfo (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:1:117489)
_addError @ background.js:1
background.js:1 this.options.mode.getValue is not a function TypeError: this.options.mode.getValue is not a function
    at Object.getFilterQuery (background.js:22)
    at Object.getRecommendationsByUrl (background.js:22)
    at Object._updateRecommended (background.js:22)
    at _tabEvent (background.js:22)
    at n._notifyListeners (background.js:1)
    at n.emit (background.js:1)
    at Object._updateTabInfo (background.js:1) Object TypeError: this.options.mode.getValue is not a function
    at Object.getFilterQuery (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:22:33232)
    at Object.getRecommendationsByUrl (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:22:32990)
    at Object._updateRecommended (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:22:34925)
    at _tabEvent (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:22:32271)
    at n._notifyListeners (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:1:102998)
    at n.emit (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:1:102700)
    at Object._updateTabInfo (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:1:117564)
_addError @ background.js:1
background.js:1 undefined Object Object "Error
    at Object._getDetailsFromObject (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:1:6527)
    at Object._addError (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:1:5886)
    at Object.logError (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:1:5694)
    at Object._sendMessage (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:1:9486)
    at async Promise.all (index 0)
    at async Object._sendMessages (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:1:9707)"
_addError @ background.js:1
background.js:1 undefined Object Object "Error
    at Object._getDetailsFromObject (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:1:6527)
    at Object._addError (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:1:5886)
    at Object.logError (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:1:5694)
    at Object._sendMessage (chrome-extension://aipncmjoigmhooiiclcailmhiopachih/js/background.js:1:9486)"
_addError @ background.js:1
```
</details>

**Comment by TylerVigario** [comment]
Same issue here. However `.getValue()`  TypeError seems to be more concerning.

When I get some time I will attempt to debug.
