### ISSUE TITLE
Always get invalid custom field error

### ISSUE THREAD

**Issue by Oberlurch3000** [marius-wieschollek/passwords-webextension#180]
Whenever I start my browser and open the passwords extention I get multiple error messages:
"Found invalid custom field."

This is what the debug window says:
{
  "details": {
    "data": {
      "field": {},
      "level": "error"
    },
    "message": "Found invalid custom field",
    "stack": "Error: Found invalid custom field\n    at Object.error (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:5294)\n    at S.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:141438)\n    at S.fromJSON (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:141310)\n    at M.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:140232)\n    at M.fromEncryptedData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:139204)\n    at kt.makePasswordFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:159164)\n    at kt.makeFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:158777)\n    at g._dataToModel (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:134610)\n    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:134471\n    at new Promise (<anonymous>)",
    "time": 1623346735804
  },
  "error": {
    "name": "Error",
    "stack": "Error: Found invalid custom field\n    at Object.error (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:5294)\n    at S.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:141438)\n    at S.fromJSON (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:141310)\n    at M.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:140232)\n    at M.fromEncryptedData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:139204)\n    at kt.makePasswordFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:159164)\n    at kt.makeFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:158777)\n    at g._dataToModel (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:134610)\n    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:134471\n    at new Promise (<anonymous>)",
    "string": "Error: Found invalid custom field",
    "message": "Found invalid custom field"
  }
}

I don't understand what could cause the issue by this messages.
Any ideas? Thanks!

**Comment by Oberlurch3000** [comment]
Solved it by exporting all passwords and importing them while overwriting all existing ones.
