### ISSUE TITLE
Edge login bug "access denied", but after a couple clicks it is actually logged in. But only after the clicks.

### ISSUE THREAD

**Issue by FernandoMarques-Santos** [marius-wieschollek/passwords-webextension#213]
### System Information
Windows 10 x64
![Version and log Nextcloud edge app](https://user-images.githubusercontent.com/33721644/153257429-ddc25ae8-8642-4483-8e03-cd74f8518fd1.jpg)

### Steps to reproduce
1. Enter password. Extension asks to click the button.
2. Click button: access denied.
2. Click out of the extension. Then Click on it again.
3. Surprisingly logged in. But only after these clicks.

See the bug in video: https://youtu.be/zMdU7P83yUk

### Expected result
Smooth login

### Actual result
Gets the user annoyed

### Browser log
<details>
background.js:2 
        
       Could not establish connection. Receiving end does not exist. Error: Could not establish connection. Receiving end does not exist.
    at I (background.js:2:760819) Objectdetails: {data: n, message: 'Could not establish connection. Receiving end does not exist.', file: undefined, line: undefined, stack: 'Error: Could not establish connection. Receiving e…hgdfpkngjcmeepdpcgpffk/js/background.js:2:760819)', …}data: n {_id: '827d11ed-1e6f-4fc1-88c5-6c311eee9426', _tab: null, _type: 'queue.items', _reply: null, _sender: 'background', …}file: undefinedline: undefinedmessage: "Could not establish connection. Receiving end does not exist."stack: "Error: Could not establish connection. Receiving end does not exist.\n    at I (chrome-extension://cjmlcljdpphgdfpkngjcmeepdpcgpffk/js/background.js:2:760819)"time: 1644422993012[[Prototype]]: Objecterror: {name: 'Error', stack: 'Error: Could not establish connection. Receiving e…hgdfpkngjcmeepdpcgpffk/js/background.js:2:760819)', string: 'Error: Could not establish connection. Receiving end does not exist.', message: 'Could not establish connection. Receiving end does not exist.'}[[Prototype]]: Object Error: Could not establish connection. Receiving end does not exist.
    at I (chrome-extension://cjmlcljdpphgdfpkngjcmeepdpcgpffk/js/background.js:2:760819)
_addError @ background.js:2
background.js:2 
        
       Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    at I (background.js:2:760819)
background.js:2 
        
       Could not establish connection. Receiving end does not exist. Error: Could not establish connection. Receiving end does not exist.
    at I (background.js:2:760819) Object Error: Could not establish connection. Receiving end does not exist.
    at I (chrome-extension://cjmlcljdpphgdfpkngjcmeepdpcgpffk/js/background.js:2:760819)
_addError @ background.js:2
background.js:2 
        
       Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    at I (background.js:2:760819)
background.js:2 
        
       Could not establish connection. Receiving end does not exist. Error: Could not establish connection. Receiving end does not exist.
    at I (background.js:2:760819) Object Error: Could not establish connection. Receiving end does not exist.
    at I (chrome-extension://cjmlcljdpphgdfpkngjcmeepdpcgpffk/js/background.js:2:760819)
_addError @ background.js:2
background.js:2 
        
       Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    at I (background.js:2:760819)

</details>

**Comment by marius-wieschollek** [comment]
might be possible that his bug only exists because i didn't update the edge extension. I have uploaded the latest version and you should see an update sometime in the next month.

**Comment by FernandoMarques-Santos** [comment]
thank you Marius. The extension is now a little more bugged as you can see from the print below.

![image](https://user-images.githubusercontent.com/33721644/154554827-4f585aaf-78d1-4045-814c-0a22af4e99cc.png)

A quick fix for me was to install the chrome version on edge, which has a more recent version if anyone is having the same problem. 

My suggestion is that, if they are exactly the same (i.e, edge version has no customization), maybe you can drop the edge version, so people don't feel that they really need to stick to that version.

**Comment by marius-wieschollek** [comment]
this looks like you have the "show language tags" setting enabled in the debug settings. disabling it should fix the issue
