### ISSUE TITLE
Chrome-Ext in Kiwi-Browser fails

### ISSUE THREAD

**Issue by robshnup** [marius-wieschollek/passwords-webextension#227]
### System Information
- Extension Version: 2.25
- App Version: Last
- Browser and Version: 101.0.4951.40
- Client OS and Version: Android 12

### Steps to reproduce
Installing the browser add-on with Kiwi-Browser is no problem. But it does not fill any fields even if you refresh the page.
In console there are only indifferent topics or mostly nothing .
But if you call the dev-tools console (with or without some messages coming from the site) and refresh the page then it fills the fields satisfying

### Expected result
The addon should fill the credentials at once
(In Windows with Firefox/Chromium/Edge everything works satisfying)

### Actual result
Nothing goes on except you delete the console and refresh the page.

### Browser log
<details>
Nothing special in the Kiwi-Log
</details>

**Comment by marius-wieschollek** [comment]
I tried installing the extension on Kiwi and got the error `Cannot read properties of null (reading 'tab')`. So i guess they changed their addon api

```
{"details":{"data":{"module":{},"message":{"id":"95e305bc-14ed-482b-9eaa-391c2ee3b990","tab":null,"type":"folder.list","reply":null,"silent":false,"sender":"popup","channel":"runtime","payload":{"server":"53fd22c1-6199-4fa4-803c-ee15dd240739","folder":"00000000-0000-0000-0000-000000000000"},"receiver":"background"},"reply":{"id":"a7b03975-2dc0-43c3-ba5d-8f120a9f914b","tab":null,"type":null,"reply":"95e305bc-14ed-482b-9eaa-391c2ee3b990","silent":false,"sender":"background","channel":"runtime","payload":null,"receiver":"popup"}},"message":"Cannot read properties of null (reading 'tab')","stack":"TypeError: Cannot read properties of null (reading 'tab')\n    at a.execute (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/FolderList.js:1:522)\n    at Object._executeController (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:858052)\n    at Array.<anonymous> (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:853560)\n    at async Object._notifyListeners (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:816636)\n    at async Object._processMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:816223)\n    at async Object._processReceivedMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:815271)","time":1657517312150},"error":{"name":"TypeError","stack":"TypeError: Cannot read properties of null (reading 'tab')\n    at a.execute (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/FolderList.js:1:522)\n    at Object._executeController (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:858052)\n    at Array.<anonymous> (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:853560)\n    at async Object._notifyListeners (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:816636)\n    at async Object._processMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:816223)\n    at async Object._processReceivedMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:815271)","string":"TypeError: Cannot read properties of null (reading 'tab')","message":"Cannot read properties of null (reading 'tab')"}}
```

**Comment by robshnup** [comment]
I didn't get that error anyways. Installed version 2.2.5 on Android 12 and installed version 2.2.4 an Android 6.1.
On both systems the extension runs as expected on without errors except the described bahaviour.
