### ISSUE TITLE
Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by kernjuri** [marius-wieschollek/passwords-webextension#247]
Hallo,

seit heute ist es nicht mehr möglich sich einzuloggen, nach Eingabe des MasterPasswortes wird man wieder zur Eingabe aufgefordert. Das Problem habe ich nur auf dem Windows Rechner, auf MacOS gibt es dieses Problem bei mir nicht.

Unter Debug finde ich diese Fehlermeldung

    },
    "message": "Could not establish connection. Receiving end does not exist.",
    "stack": "Error: Could not establish connection. Receiving end does not exist.\n    at I (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:748828)",
    "time": 1671125708692
  },
  "error": {
    "name": "Error",
    "stack": "Error: Could not establish connection. Receiving end does not exist.\n    at I (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:748828)",
    "string": "Error: Could not establish connection. Receiving end does not exist.",
    "message": "Could not establish connection. Receiving end does not exist."
  }

Extension Version
2.2.6.4550 und 2.2.6.4663
Zielplattform
Chrome
Extension Modus
Production
User Agent
Google Chrome 108.0.0.0 / Desktop Windows amd64 / Version 108.0.5359.125 (Offizieller Build) (64-Bit)
ID des Ordners für private Passwörter

**Comment by kernjuri** [comment]
Das Problem besteht nicht mehr, nach dem ich die neuen Windows-Updates installiert habe.
