### ISSUE TITLE
First connection to Nextcloud instance

### ISSUE THREAD

**Issue by amr21code** [marius-wieschollek/passwords-webextension#263]
cant connect to my nextcloud anymore over chrome based browsers brave and chrome. firefox working fine.
happened after an update. worked for a while on a nightly build 2-3 months ago and is now broken again (for a couple of weeks now)

### System Information
- Extension Version: 2.3.1
- App Version: 2023.8.31
- Browser and Version: 
Brave 1.58.124 (Chromium: 117.0.5938.62 64bit)
(Chrome has a different problem so Brave for now)
- Client OS and Version: Windows 10 22H2

### Steps to reproduce
1. Installed the extension through the store
2. right click on the icon -> options
3. click on add button
4. fill out name/url/user/app-pw
5. click on save
6. error message (red popup: speichern fehlgeschlagen. Verbindung mit URL nicht möglich)
7. debug log shows failed to fetch, passwordsclient not found, no default configured

### Expected result
account added to the extension and is usable

### Actual result

debug log:
```{
  "details": {
    "data": {},
    "message": "Failed to fetch",
    "stack": "TypeError: Failed to fetch\n    at O._executeRequest (chrome-extension://extensionid/js/background.js:2:572610)\n    at O.send (chrome-extension://extensionid/js/background.js:2:570827)\n    at K.load (chrome-extension://extensionid/js/background.js:2:574320)\n    at h._checkConnection (chrome-extension://extensionid/js/ServerCreate.js:1:3200)\n    at h.validate (chrome-extension://extensionid/js/ServerCreate.js:1:1082)\n    at async o.execute (chrome-extension://extensionid/js/ServerCreate.js:1:401)\n    at async Object._executeController (chrome-extension://extensionid/js/background.js:2:865820)\n    at async Array.<anonymous> (chrome-extension://extensionid/js/background.js:2:862062)\n    at async Object._notifyListeners (chrome-extension://extensionid/js/background.js:2:823641)\n    at async Object._processMessage (chrome-extension://extensionid/js/background.js:2:823228)",
    "time": 1694708701235
  },
  "error": {
    "name": "TypeError",
    "stack": [
      "TypeError: Failed to fetch",
      "    at O._executeRequest (chrome-extension://extensionid/js/background.js:2:572610)",
      "    at O.send (chrome-extension://extensionid/js/background.js:2:570827)",
      "    at K.load (chrome-extension://extensionid/js/background.js:2:574320)",
      "    at h._checkConnection (chrome-extension://extensionid/js/ServerCreate.js:1:3200)",
      "    at h.validate (chrome-extension://extensionid/js/ServerCreate.js:1:1082)",
      "    at async o.execute (chrome-extension://extensionid/js/ServerCreate.js:1:401)",
      "    at async Object._executeController (chrome-extension://extensionid/js/background.js:2:865820)",
      "    at async Array.<anonymous> (chrome-extension://extensionid/js/background.js:2:862062)",
      "    at async Object._notifyListeners (chrome-extension://extensionid/js/background.js:2:823641)",
      "    at async Object._processMessage (chrome-extension://extensionid/js/background.js:2:823228)"
    ],
    "string": "TypeError: Failed to fetch",
    "message": "Failed to fetch"
  }
}


{
  "details": {
    "data": {},
    "message": "PasswordsClient not found",
    "stack": "Error: PasswordsClient not found\n    at Object.findById (chrome-extension://extensionid/js/background.js:2:792228)\n    at async Object.getDefaultApi (chrome-extension://extensionid/js/background.js:2:774065)\n    at async d.execute (chrome-extension://extensionid/js/DebugExtensionInfo.js:1:568)\n    at async Object._executeController (chrome-extension://extensionid/js/background.js:2:865820)\n    at async Array.<anonymous> (chrome-extension://extensionid/js/background.js:2:863202)\n    at async Object._notifyListeners (chrome-extension://extensionid/js/background.js:2:823641)\n    at async Object._processMessage (chrome-extension://extensionid/js/background.js:2:823228)\n    at async Object._processReceivedMessage (chrome-extension://extensionid/js/background.js:2:822276)",
    "time": 1694708703192
  },
  "error": {
    "name": "Error",
    "stack": [
      "Error: PasswordsClient not found",
      "    at Object.findById (chrome-extension://extensionid/js/background.js:2:792228)",
      "    at async Object.getDefaultApi (chrome-extension://extensionid/js/background.js:2:774065)",
      "    at async d.execute (chrome-extension://extensionid/js/DebugExtensionInfo.js:1:568)",
      "    at async Object._executeController (chrome-extension://extensionid/js/background.js:2:865820)",
      "    at async Array.<anonymous> (chrome-extension://extensionid/js/background.js:2:863202)",
      "    at async Object._notifyListeners (chrome-extension://extensionid/js/background.js:2:823641)",
      "    at async Object._processMessage (chrome-extension://extensionid/js/background.js:2:823228)",
      "    at async Object._processReceivedMessage (chrome-extension://extensionid/js/background.js:2:822276)"
    ],
    "string": "Error: PasswordsClient not found",
    "message": "PasswordsClient not found"
  }
}

{
  "details": {
    "data": {},
    "message": "No default configured",
    "stack": "Error: No default configured\n    at Object.getDefaultApi (chrome-extension://extensionid/js/background.js:2:774228)\n    at async d.execute (chrome-extension://extensionid/js/DebugExtensionInfo.js:1:568)\n    at async Object._executeController (chrome-extension://extensionid/js/background.js:2:865820)\n    at async Array.<anonymous> (chrome-extension://extensionid/js/background.js:2:863202)\n    at async Object._notifyListeners (chrome-extension://extensionid/js/background.js:2:823641)\n    at async Object._processMessage (chrome-extension://extensionid/js/background.js:2:823228)\n    at async Object._processReceivedMessage (chrome-extension://extensionid/js/background.js:2:822276)",
    "time": 1694708703193
  },
  "error": {
    "name": "Error",
    "stack": [
      "Error: No default configured",
      "    at Object.getDefaultApi (chrome-extension://extensionid/js/background.js:2:774228)",
      "    at async d.execute (chrome-extension://extensionid/js/DebugExtensionInfo.js:1:568)",
      "    at async Object._executeController (chrome-extension://extensionid/js/background.js:2:865820)",
      "    at async Array.<anonymous> (chrome-extension://extensionid/js/background.js:2:863202)",
      "    at async Object._notifyListeners (chrome-extension://extensionid/js/background.js:2:823641)",
      "    at async Object._processMessage (chrome-extension://extensionid/js/background.js:2:823228)",
      "    at async Object._processReceivedMessage (chrome-extension://extensionid/js/background.js:2:822276)"
    ],
    "string": "Error: No default configured",
    "message": "No default configured"
  }
}

### Browser log


`background.js:2  GET https://url/index.php/apps/passwords/api/1.0/session/request net::ERR_FAILED
_executeRequest @ background.js:2
send @ background.js:2
load @ background.js:2
_checkConnection @ ServerCreate.js:1
validate @ ServerCreate.js:1
await in validate (async)
execute @ ServerCreate.js:1
_executeController @ background.js:2
(anonymous) @ background.js:2
await in (anonymous) (async)
_notifyListeners @ background.js:2
_processMessage @ background.js:2
_processReceivedMessage @ background.js:2
await in _processReceivedMessage (async)
(anonymous) @ background.js:2
_receiveMessage @ background.js:2
r.Z.getArea.r.Z.AREA_BACKGROUND.window.inboxMessage @ background.js:2
_sendMessage @ js/options.js:2
(anonymous) @ js/options.js:2
send @ js/options.js:2
save @ js/options.js:2
create @ js/options.js:2
click @ js/options.js:2
Qt @ js/options.js:2
r @ js/options.js:2
Qt @ js/options.js:2
e.$emit @ js/options.js:2
fireEvent @ js/options.js:2
click @ js/options.js:2
Qt @ js/options.js:2
r @ js/options.js:2
Cs.a._wrapper @ js/options.js:2


background.js:2 Failed to fetch TypeError: Failed to fetch
    at O._executeRequest (background.js:2:572610)
    at O.send (background.js:2:570827)
    at K.load (background.js:2:574320)
    at h._checkConnection (ServerCreate.js:1:3200)
    at h.validate (ServerCreate.js:1:1082)
    at async o.execute (ServerCreate.js:1:401)
    at async Object._executeController (background.js:2:865820)
    at async Array.<anonymous> (background.js:2:862062)
    at async Object._notifyListeners (background.js:2:823641)
    at async Object._processMessage (background.js:2:823228) {details: {…}, error: {…}} TypeError: Failed to fetch
    at O._executeRequest (chrome-extension://extensionid/js/background.js:2:572610)
    at O.send (chrome-extension://extensionid/js/background.js:2:570827)
    at K.load (chrome-extension://extensionid/js/background.js:2:574320)
    at h._checkConnection (chrome-extension://extensionid/js/ServerCreate.js:1:3200)
    at h.validate (chrome-extension://extensionid/js/ServerCreate.js:1:1082)
    at async o.execute (chrome-extension://extensionid/js/ServerCreate.js:1:401)
    at async Object._executeController (chrome-extension://extensionid/js/background.js:2:865820)
    at async Array.<anonymous> (chrome-extension://extensionid/js/background.js:2:862062)
    at async Object._notifyListeners (chrome-extension://extensionid/js/background.js:2:823641)
    at async Object._processMessage (chrome-extension://extensionid/js/background.js:2:823228)
_addError @ background.js:2
logError @ background.js:2
_checkConnection @ ServerCreate.js:1
await in _checkConnection (async)
validate @ ServerCreate.js:1
await in validate (async)
execute @ ServerCreate.js:1
_executeController @ background.js:2
(anonymous) @ background.js:2
await in (anonymous) (async)
_notifyListeners @ background.js:2
_processMessage @ background.js:2
_processReceivedMessage @ background.js:2
await in _processReceivedMessage (async)
(anonymous) @ background.js:2
_receiveMessage @ background.js:2
r.Z.getArea.r.Z.AREA_BACKGROUND.window.inboxMessage @ background.js:2
_sendMessage @ js/options.js:2
(anonymous) @ js/options.js:2
send @ js/options.js:2
save @ js/options.js:2
create @ js/options.js:2
click @ js/options.js:2
Qt @ js/options.js:2
r @ js/options.js:2
Qt @ js/options.js:2
e.$emit @ js/options.js:2
fireEvent @ js/options.js:2
click @ js/options.js:2
Qt @ js/options.js:2
r @ js/options.js:2
Cs.a._wrapper @ js/options.js:2`

**Comment by marius-wieschollek** [comment]
> PasswordsClient not found
> No default configured

These errors look like there is either no account at all or the default server setting is invalid. Can you check the extension settings?
