### ISSUE TITLE
"No Elements Found" 

### ISSUE THREAD

**Issue by Fickdichhurensohn** [marius-wieschollek/passwords-webextension#264]
### System Information
- Extension Version: 2.3.1
- App Version: ? (managed by hosting company)
- Browser and Version: Firefox
- Client OS and Version: Windows 11

The initial setup works w/o problems. Assign a app password in the nextcloud web interface. login. 
All passwords are here, extension works w/o issues.
After closing the browswer for the first time however, it stops working:
While my account still shows up, when clicking on it, it tells me there are "no elements found". 

I do not believe this is due to the setup on the hosting end, as in the web interface all passwords show up without issue. Same thing when using the android NC password app.

Any help would be greatly appreciated!

### Browser log
<details>
<summary>Content-Security-Policy: The page's settings blocked the loading of a resource at wasm-eval ("script-src"). [background.js:2:533714](moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js)
NetworkError when attempting to fetch resource. TypeError: NetworkError when attempting to fetch resource. 
Object { details: {…}, error: {…} }
 <empty string> [background.js:2:732369](moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js)
Uncaught (in promise) TypeError: can't access dead object
5
this._authQueue is null TypeError: this._authQueue is null
    addServer moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2
 
Object { details: {…}, error: {…} }
 addServer@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2:747020
[background.js:2:732369](moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js)
this._processingQueue is null TypeError: this._processingQueue is null
    addPassword moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2
    execute moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/PasswordMine.js:1
    _executeController moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2
    _initBackgroundControllers moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2
 
Object { details: {…}, error: {…} }
 addPassword@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2:734291
execute@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/PasswordMine.js:1:351
_executeController@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2:839510
_initBackgroundControllers/<@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2:834261
[background.js:2:732369](moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js)
this._processingQueue is null TypeError: this._processingQueue is null
    addPassword moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2
    execute moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/PasswordMine.js:1
    _executeController moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2
    _initBackgroundControllers moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2
 
Object { details: {…}, error: {…} }
 addPassword@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2:734291
execute@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/PasswordMine.js:1:351
_executeController@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2:839510
_initBackgroundControllers/<@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2:834261
[background.js:2:732369](moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js)
this._processingQueue is null TypeError: this._processingQueue is null
    addPassword moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2
    execute moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/PasswordMine.js:1
    _executeController moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2
    _initBackgroundControllers moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2
 
Object { details: {…}, error: {…} }
 addPassword@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2:734291
execute@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/PasswordMine.js:1:351
_executeController@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2:839510
_initBackgroundControllers/<@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2:834261
[background.js:2:732369](moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js)
this._processingQueue is null TypeError: this._processingQueue is null
    addPassword moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2
    execute moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/PasswordMine.js:1
    _executeController moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2
    _initBackgroundControllers moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2
 
Object { details: {…}, error: {…} }
 addPassword@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2:734291
execute@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/PasswordMine.js:1:351
_executeController@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2:839510
_initBackgroundControllers/<@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2:834261
[background.js:2:732369](moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js)

​</summary>

```
In Firefox:
 - Open about:debugging#/runtime/this-firefox
 - Click "Inspect" on the extension
 - Copy the content from the "Console" tab

In Chrome
 - Open chrome://extensions
 - Enable "Developer mode" in the top right corner
 - Click "Background page" on the extension
 - Copy the content from the "Console" tab
```
</details>

**Comment by marius-wieschollek** [comment]
That's a lot of errors.
Can you add the details of that "NetworkError when attempting to fetch resource. TypeError: NetworkError when attempting to fetch resource." ?
The error may also be easier to copy if you check the log in the "Debug" tab in the Addon settings

**Comment by Fickdichhurensohn** [comment]
Hi

Not sure if im giving you what you need, but in the Debu tab in the addon settings i get the following error, over and over agian:

"{"details":{"data":{"id":"66377a9b-6a61-428e-8ac5-9764c8c00e7d","tab":null,"type":"queue.items","reply":null,"silent":false,"sender":"background","channel":"runtime","payload":{"name":"mine-process","items":[{"id":"30c372be-210a-4a0e-a633-a1acd1a9a911","task":{"url":"https://nextcloud.webo.hosting/","title":"Nextcloud by Webo.hosting","password":{"selector":"#password","value":"Velofahren.2022"},"user":{"selector":"#user","value":"OrangeKodak"}},"result":{},"success":null,"cancelled":false}]},"receiver":"background"},"message":"Could not establish connection. Receiving end does not exist.","file":"moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js","line":2,"stack":"_sendMessage@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2:796031\n","time":1696452606779},"error":{"name":"Error","stack":["_sendMessage@moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js:2:796031",""],"string":"Error: Could not establish connection. Receiving end does not exist.","fileName":"moz-extension://66af8588-ba26-4f4c-83e2-5e71e1ba0440/js/background.js","lineNumber":2,"columnNumber":796031,"message":"Could not establish connection. Receiving end does not exist."}}"

**Comment by marius-wieschollek** [comment]
No, that was not the error i'm looking for.

I'm pretty sure that the log message you posted contains your actual Nextcloud Login information, so i removed it and you should change that ASAP.

**Comment by Fickdichhurensohn** [comment]
The lack of sleep is getting to me. Thanks for letting me know, changed it just to be sure.

Ill check again tonight if i can get the error.

But also it suddenly started working again, atleast for acouple of hours... Not sure whats up.

The NC password app for android works super reliable, never had that there.

**Comment by Fickdichhurensohn** [comment]
{"details":{"data":{},"message":"Cannot read properties of null (reading 'push')","stack":"TypeError: Cannot read properties of null (reading 'push')\n    at Object.addPassword (chrome-extension://cjmlcljdpphgdfpkngjcmeepdpcgpffk/js/background.js:2:760535)\n    at d.execute (chrome-extension://cjmlcljdpphgdfpkngjcmeepdpcgpffk/js/PasswordMine.js:1:351)\n    at Object._executeController (chrome-extension://cjmlcljdpphgdfpkngjcmeepdpcgpffk/js/background.js:2:864533)\n    at Array.<anonymous> (chrome-extension://cjmlcljdpphgdfpkngjcmeepdpcgpffk/js/background.js:2:859284)\n    at async Object._notifyListeners (chrome-extension://cjmlcljdpphgdfpkngjcmeepdpcgpffk/js/background.js:2:823084)\n    at async Object._processMessage (chrome-extension://cjmlcljdpphgdfpkngjcmeepdpcgpffk/js/background.js:2:822671)\n    at async Object._processReceivedMessage (chrome-extension://cjmlcljdpphgdfpkngjcmeepdpcgpffk/js/background.js:2:821719)","time":1697295450130},"error":{"name":"TypeError","stack":["TypeError: Cannot read properties of null (reading 'push')","    at Object.addPassword (chrome-extension://cjmlcljdpphgdfpkngjcmeepdpcgpffk/js/background.js:2:760535)","    at d.execute (chrome-extension://cjmlcljdpphgdfpkngjcmeepdpcgpffk/js/PasswordMine.js:1:351)","    at Object._executeController (chrome-extension://cjmlcljdpphgdfpkngjcmeepdpcgpffk/js/background.js:2:864533)","    at Array.<anonymous> (chrome-extension://cjmlcljdpphgdfpkngjcmeepdpcgpffk/js/background.js:2:859284)","    at async Object._notifyListeners (chrome-extension://cjmlcljdpphgdfpkngjcmeepdpcgpffk/js/background.js:2:823084)","    at async Object._processMessage (chrome-extension://cjmlcljdpphgdfpkngjcmeepdpcgpffk/js/background.js:2:822671)","    at async Object._processReceivedMessage (chrome-extension://cjmlcljdpphgdfpkngjcmeepdpcgpffk/js/background.js:2:821719)"],"string":"TypeError: Cannot read properties of null (reading 'push')","message":"Cannot read properties of null (reading 'push')"}}

**Comment by Fickdichhurensohn** [comment]
Hi so i tried switching to edge, mainly due to the better power managment and battery lifetime, and i get the exact same problem. These are the three types of errors i see in the debug window.

**Comment by acidicX** [comment]
@marius-wieschollek and @Fickdichhurensohn (lol) I think I just found the source of this error. It's the setting "always use private browsing mode" in Firefox, which triggered the same behavior for me. 

I've switched to save nothing & delete on exit, which is basically the same, and now the extension works again.
