### ISSUE TITLE
2.4.0 Not working with Vivaldi

### ISSUE THREAD

**Issue by admorgan** [marius-wieschollek/passwords-webextension#269]
### System Information
- Extension Version: 2.4.0 (Nov 20th 2023)
- App Version: 2023.11.30
- Browser and Version: Vivaldi 6.4.3160.44
- Client OS and Version: OpenSUSE Tumbleweed

### Steps to reproduce
1. Click on extension icon and displays a blank window
2. Open extension options and it displays a blank windows with a scroll bar

### Expected result
Display passwords/settings

### Actual result
Display does not have any content

### Browser log
<details>
<summary>Browser log</summary>

```
Uncaught TypeError: Illegal invocation
    at Object.generate (background.js:2:754158)
    at new s (background.js:2:776367)
    at Object._validateMessage (background.js:2:814295)
    at Object.send (background.js:2:811230)
    at l._fetchInitialItems (background.js:2:787113)
    at l._fetchInitialItems (background.js:2:816300)
    at new a (background.js:2:786724)
    at new l (background.js:2:815561)
    at new <anonymous> (background.js:2:815845)
    at 6765 (background.js:2:815779)
```
</details>

**Comment by admorgan** [comment]
This worked fine early this morning. Same version of the extension is working with Firefox.

**Comment by marius-wieschollek** [comment]
If you go to `vivaldi://extensions/` and click the "Update" button manually, Vivaldi should fetch the latest version which doesn't have this issue.

**Comment by admorgan** [comment]
Update fixed everything. Thank you!
