### ISSUE TITLE
[BUG]: Can not index "undefined" as "text"  2024.9.20 on NC30

### ISSUE THREAD

**Issue by humberg** [marius-wieschollek/passwords-webextension#291]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [ ] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "30.0.1.2",
        "app": "2024.9.20",
        "lsr": false,
        "php": "8.2.23",
        "cronPhp": "8.2.24"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": false,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "default",
        "previews": "default",
        "security": "hibp",
        "words": "auto",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

### Client Information

Browser and Version: Chrome 130.0.6723.71
Client OS and Version: Win10 

### Bug description

Start Chrome
Go to Website with Password
After a few seconds the Password Sign is active - I can use Passwords

....
Working 
....

I open a new Tab in Chrome
Go to (same) Website
The Password Sign tells me "No Passwords"
I open Passwords - Discover - refresh my Server
Wait
I can use Passwords for 2..3 minutes

--

Chrome - AddOn - Debug:
 Can not index "undefined" as "text"

{
  "details": {
    "data": {
      "level": "warning"
    },
    "message": "Can not index \"undefined\" as \"text\"",
    "stack": "Error: Can not index \"undefined\" as \"text\"\n    at Object.warning (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:815085)\n    at g.addFieldValue (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:917278)\n    at l._indexUrl (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:919216)\n    at l._createIndex (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:918244)\n    at l.indexItem (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:918051)\n    at p.add (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:919935)\n    at Object._addItem (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:929826)\n    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:929103\n    at Array.forEach (<anonymous>)\n    at Object.add (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:929085)",
    "time": 1730275813884
  },
  "error": {
    "name": "Error",
    "stack": [
      "Error: Can not index \"undefined\" as \"text\"",
      "    at Object.warning (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:815085)",
      "    at g.addFieldValue (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:917278)",
      "    at l._indexUrl (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:919216)",
      "    at l._createIndex (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:918244)",
      "    at l.indexItem (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:918051)",
      "    at p.add (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:919935)",
      "    at Object._addItem (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:929826)",
      "    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:929103",
      "    at Array.forEach (<anonymous>)",
      "    at Object.add (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:929085)"
    ],
    "string": "Error: Can not index \"undefined\" as \"text\"",
    "message": "Can not index \"undefined\" as \"text\""
  }
}

### Steps to reproduce

see below

### Expected behavior

see below

**Comment by buchez4281** [comment]
I believe I'm having a similar issue. I went to access the Chrome extension this morning and received an error. Thinking it was a Chrome/extension NC compatibility issue I went down the route of updating NC from v26 to v29. I've been meaning to do that anyways. Now I'm not able to link the extension to NC.

In the extensions debug, on initial startup (before I try and enter any login information) I see 2 debug messages:

```
{
  "details": {
    "data": {},
    "message": "PasswordsClient not found",
    "stack": "Error: PasswordsClient not found\n    at Object.findById (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:881453)\n    at async Object.getDefaultApi (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:836452)\n    at async Object._getSettingsRepository (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:979304)\n    at async Object._getServerSetting (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:979130)\n    at async Object._serverGet (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:978438)\n    at async Object.get (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:976576)\n    at async Object.get (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:930493)",
    "time": 1730494371478
  },
  "error": {
    "name": "Error",
    "stack": [
      "Error: PasswordsClient not found",
      "    at Object.findById (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:881453)",
      "    at async Object.getDefaultApi (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:836452)",
      "    at async Object._getSettingsRepository (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:979304)",
      "    at async Object._getServerSetting (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:979130)",
      "    at async Object._serverGet (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:978438)",
      "    at async Object.get (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:976576)",
      "    at async Object.get (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:930493)"
    ],
    "string": "Error: PasswordsClient not found",
    "message": "PasswordsClient not found"
  }
}
```

and

```
{
  "details": {
    "data": {},
    "message": "No default configured",
    "stack": "Error: No default configured\n    at Object.getDefaultApi (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:836615)\n    at async Object._getSettingsRepository (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:979304)\n    at async Object._getServerSetting (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:979130)\n    at async Object._serverGet (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:978438)\n    at async Object.get (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:976576)\n    at async Object.get (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:930493)",
    "time": 1730494509592
  },
  "error": {
    "name": "Error",
    "stack": [
      "Error: No default configured",
      "    at Object.getDefaultApi (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:836615)",
      "    at async Object._getSettingsRepository (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:979304)",
      "    at async Object._getServerSetting (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:979130)",
      "    at async Object._serverGet (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:978438)",
      "    at async Object.get (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:976576)",
      "    at async Object.get (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:930493)"
    ],
    "string": "Error: No default configured",
    "message": "No default configured"
  }
}
```
When I try and enter my connection details I see this debug message:

```
{
  "details": {
    "data": {},
    "message": "Failed to fetch",
    "stack": "TypeError: Failed to fetch\n    at O._executeRequest (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:575430)\n    at O.send (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:573441)\n    at K.load (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:576980)\n    at g._checkConnection (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:947829)\n    at g.validate (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:945711)\n    at async o.execute (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:794117)\n    at async Object._executeController (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:969144)\n    at async Array.<anonymous> (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:964592)\n    at async Object._notifyListeners (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:907622)\n    at async Object._processMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:907209)",
    "time": 1730494750189
  },
  "error": {
    "name": "TypeError",
    "stack": [
      "TypeError: Failed to fetch",
      "    at O._executeRequest (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:575430)",
      "    at O.send (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:573441)",
      "    at K.load (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:576980)",
      "    at g._checkConnection (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:947829)",
      "    at g.validate (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:945711)",
      "    at async o.execute (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:794117)",
      "    at async Object._executeController (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:969144)",
      "    at async Array.<anonymous> (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:964592)",
      "    at async Object._notifyListeners (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:907622)",
      "    at async Object._processMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:907209)"
    ],
    "string": "TypeError: Failed to fetch",
    "message": "Failed to fetch"
  }
}

```
At this point I'm assuming its something with the extension. I did test with Edge but had the same issue. From my Android phone I can access my PW through that app though I believe that is different but proves that Passwords on NC is working and accessible over the network.

**Comment by humberg** [comment]
Here some additional error-messages from the addOn.
It seems, that the AddOn is trying to connect to Server, but the server gives a 429 error.
This is after the update to NC 30 and AddOn 3.0



Unchecked runtime.lastError: Cannot create item with duplicate id d042845e-b400-492a-9ee2-071a46786ebc
Kontext
Unbekannt
Stacktrace
:0 (Anonyme Funktion)
Du hast keine Benachrichtigungen.
No tab with id: 1121382279. Error: No tab with id: 1121382279. [object Object] Error: No tab with id: 1121382279.
HTTP 429 - Too Many Requests TooManyRequestsError: HTTP 429 - Too Many Requests [object Object] TooManyRequestsError: HTTP 429 - Too Many Requests at f.getClass (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:558803) at _.getClass (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:622342) at O._getHttpError (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:575959) at O.send (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:573668) at async K.authorize (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:577864) at async u._tryAutomaticAuth (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:832860) at async u._tryAuthorization (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:832468) at async u.authorize (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:832277) at async Object.addServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:835298) at async Object.reloadServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:835893)
Uncaught (in promise) ReferenceError: server is not defined
Client file3 is not authorized ClientNotAuthorizedError: Client file3 is not authorized [object Object] ClientNotAuthorizedError: Client file3 is not authorized at c.getHiddenFolder (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:807651) at Object._loadHiddenPasswords (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:959794) at Object._reloadServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:959281) at async Object._addServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:958868) at async chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:958475 at async s._notifyListeners (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:805125) at async s.emit (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:804820) at async Object.addServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:835597) at async Object.reloadServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:835893) at async n.execute (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:796129)
Unchecked runtime.lastError: Cannot create item with duplicate id 17775e76-4149-46dc-9fb6-ade8e131c893
Unchecked runtime.lastError: Cannot create item with duplicate id de560419-bd0a-492d-9a4d-0c4a15852b18
Unchecked runtime.lastError: Cannot create item with duplicate id 87ae920f-c2c8-4c35-8524-2d409c1fe918
No tab with id: 1121382323. Error: No tab with id: 1121382323. [object Object] Error: No tab with id: 1121382323.
Unchecked runtime.lastError: Cannot create item with duplicate id 5b9cbea6-5409-44f6-9868-bc9e0da94cd1
Unchecked runtime.lastError: Cannot create item with duplicate id 38efe6df-d413-473f-bc7b-b7bc70dca1ad
Unchecked runtime.lastError: Cannot create item with duplicate id 38c7d60e-9532-4a2b-accd-cc10aa96ee6f
Unchecked runtime.lastError: Cannot create item with duplicate id 2f4b4db9-e1a4-489d-a7f6-ec025fa34a7a
Unchecked runtime.lastError: Cannot create item with duplicate id 4c973a37-7c8a-45e5-88d3-9668b62f6acf
Unchecked runtime.lastError: Cannot create item with duplicate id 99c7b858-cd0c-42b3-b555-57791f56234c
Unchecked runtime.lastError: Cannot create item with duplicate id aa1aa65d-ad79-4837-a793-058b45d05423
Unchecked runtime.lastError: Cannot create item with duplicate id 4c6630c1-1bd3-4d73-8038-de36a058f447
Unchecked runtime.lastError: Cannot create item with duplicate id 22fd5083-377e-4477-905a-063dd0ff22df
Unchecked runtime.lastError: Cannot create item with duplicate id 07fdc23b-c7db-4596-b342-79f7a0f49ee1
No tab with id: 1121383634. Error: No tab with id: 1121383634. [object Object] Error: No tab with id: 1121383634.
No tab with id: 1121383697. Error: No tab with id: 1121383697. [object Object] Error: No tab with id: 1121383697.
No tab with id: 1121383701. Error: No tab with id: 1121383701. [object Object] Error: No tab with id: 1121383701.
Unchecked runtime.lastError: Cannot create item with duplicate id 57f89466-2875-4afe-bea3-9d223d763b83
Unchecked runtime.lastError: The page keeping the extension port is moved into back/forward cache, so the message channel is closed.
Unable to download all specified images. Error: Unable to download all specified images. [object Object] Error: Unable to download all specified images. at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:773853 at extensions::notifications:122:7 at Object.oncomplete (extensions::notifications:95:9) at Object.onerror (extensions::imageUtil:124:17) at extensions::imageUtil:62:17
Failed to fetch TypeError: Failed to fetch [object Object] TypeError: Failed to fetch at O._executeRequest (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:575430) at O.send (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:573441) at i.findByNames (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:562944) at Object._getColors (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:894875) at Object.create (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:893351) at Object.loadServerThemes (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:897285) at async Object._listThemes (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:896576) at async Object.findById (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:896243) at async Object.getCurrentTheme (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:939992) at async Object.getBadgeBackgroundColor (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:939623)
Failed to fetch TypeError: Failed to fetch [object Object] TypeError: Failed to fetch at O._executeRequest (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:575430) at O.send (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:573441) at i.findByName (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:562792) at g.check (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:809007) at Object.addServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:835271) at async Promise.all (index 0) at async Object._loadServers (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:835104)
A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received [object Object] Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received at h (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:776309)
HTTP 429 - Too Many Requests TooManyRequestsError: HTTP 429 - Too Many Requests [object Object] TooManyRequestsError: HTTP 429 - Too Many Requests at f.getClass (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:558803) at _.getClass (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:622342) at O._getHttpError (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:575959) at O.send (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:573668) at async K.authorize (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:577864) at async u._tryAutomaticAuth (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:832860) at async u._tryAuthorization (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:832468) at async u.authorize (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:832277) at async Object.addServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:835298) at async Object.restartSession (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:836015)
Client file3 is not authorized ClientNotAuthorizedError: Client file3 is not authorized [object Object] ClientNotAuthorizedError: Client file3 is not authorized at c.getHiddenFolder (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:807651) at Object._loadHiddenPasswords (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:959794) at Object._reloadServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:959281) at async Object._addServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:958868) at async chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:958475 at async s._notifyListeners (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:805125) at async s.emit (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:804820) at async Object.addServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:835597) at async Object.restartSession (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:836015) at async Object._reloadServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:959105)
Unchecked runtime.lastError: Cannot create item with duplicate id 5d34c02a-cc75-491a-b80a-9a5c9693f301
Unchecked runtime.lastError: Cannot create item with duplicate id f030d6fa-66e8-44b7-8b75-8eaa32aaa71d
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
Could not establish connection. Receiving end does not exist. Error: Could not establish connection. Receiving end does not exist. [object Object] Error: Could not establish connection. Receiving end does not exist. at h (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:776309)
Client file3 is not authorized ClientNotAuthorizedError: Client file3 is not authorized [object Object] ClientNotAuthorizedError: Client file3 is not authorized at c.getHiddenFolder (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:807651) at Object._loadHiddenPasswords (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:959794) at Object._reloadServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:959281) at async Object._addServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:958868) at async chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:958475 at async s._notifyListeners (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:805125) at async s.emit (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:804820) at async Object.addServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:835597) at async Promise.all (index 0) at async Object._loadServers (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:835104)
Can not index "undefined" as "text" Error: Can not index "undefined" as "text" [object Object] Error: Can not index "undefined" as "text" at Object.warning (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:815085) at g.addFieldValue (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:917278) at l._indexUrl (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:919216) at l._createIndex (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:918244) at l.indexItem (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:918051) at p.add (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:919935) at Object._addItem (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:929826) at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:929103 at Array.forEach (<anonymous>) at Object.add (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:929085)
